//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

namespace HarryPotter.Magics
{
	public class KMagic : OffensiveMagic
	{	
		public GameObject hand;
		public GameObject lightningObject;
		
		public KMagic (string magicName, int cooldown) : base(magicName)
		{
			sprite = sprite = Resources.Load<Sprite> ("purpleLightning");
			hand = GameObject.FindGameObjectWithTag ("hand");
			if (hand == null)
				Debug.Log ("null hand");
			lightningObject = GameObject.FindGameObjectWithTag ("purple");
			if (lightningObject == null)
				Debug.Log ("null lightningObject");
			this.cooldown = cooldown;
		}
		
		public override void Effect()
		{
			Debug.Log ("EFFECT K !!!");
			GameObject lightning = (GameObject)MonoBehaviour.Instantiate(lightningObject);
			lightning.tag = "purpleLight";	
			MonoBehaviour.Destroy ( lightning , 5f);
		}

		public void End()
		{
			Magic.casting = false;
		}
	}
}


