//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace HarryPotter.Magics
{
	public class ZMagicMono : MonoBehaviour
	{
		bool isColided = false;
		Rigidbody rigid;
		
		Vector3 velocity = Vector3.forward * 10;
		// Use this for initialization
		void Start () {

			Physics.IgnoreCollision (this.GetComponent<Collider> (), GameObject.FindGameObjectWithTag ("Player").GetComponent<Collider>()); 
						
			rigid = GetComponent<Rigidbody> ();
		}
		
		// Update is called once per frame
		void Update () {
		/*	if (isColided) {
				foreach (var b in this.GetComponentsInChildren<ParticleSystem>()) {
					if(b.name == "KYexplosion") transform.localScale = b.transform.localScale;
				}
				
				Debug.Log( GetComponent<SphereCollider>().radius );
				//GetComponent<Collider>().transform.localScale += 0.1f * Vector3.one;
				GetComponent<SphereCollider>().radius += 0.2f ;
				Debug.Log( GetComponent<Collider>() );
				Debug.Log( GetComponent<Collider>().transform );
				Debug.Log( GetComponent<Collider>().transform.localScale );
				
			}
			else
				transform.position += velocity * Time.deltaTime;*/
			
			
		}
		
		//void OnTriggerEnter(Collision collision) {

			/*if (collision.rigidbody.gameObject.tag == "Deementor") {
				collision.rigidbody.AddForce(Vector3.up); 
				
			}

				//GetComponent<Rigidbody>().isKinematic = true;
			//GetComponent<Rigidbody>().detectCollisions = false;
			
			Debug.Log ("collision ! " + collision);
			
			if (isColided)
				return;
			
			isColided = true;
			
			Physics.IgnoreCollision (this.GetComponent<Collider> (), GameObject.FindGameObjectWithTag ("Floor").GetComponent<Collider>()); 
			
			foreach (var b in this.GetComponentsInChildren<ParticleSystem>()) {
				if (b.name == "KYexplosion" || b.name == "KYcircle" || b.name == "KYflash") {
					Debug.Log("playyy !!!!");
					b.Play ();
				}
			}
			
			Destroy (this.gameObject,1f);*/
		//}

	}
}

