//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace HarryPotter.Magics
{
	public class ZMagic : OffensiveMagic
	{
		public float blastRepeat ;

		public ZMagic (string magicName, int cooldown) : base(magicName)
		{
			sprite = sprite = Resources.Load<Sprite> ("blast");
			//blastEffect = GameObject.FindGameObjectWithTag ("blast");
			//if (blastEffect == null)
			//	Debug.Log ("null blastEffect");
			this.cooldown = cooldown;
		}

		public override void Effect()
		{
			Debug.Log ("EFFECT ZZZZZZZZZZ");

			GameObject.FindGameObjectWithTag ("Scripts").GetComponent<CreateBullets> ().ThrowZMagic ();

		}
	}
}

