//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

namespace HarryPotter.Magics
{
	public static class MagicFactory
	{
		private static Dictionary<string, Magic> magics = new Dictionary<string, Magic>();

		public static Magic GetMagic(string magic)
		{
			return magics [magic];
		}

		public static void AddMagic(string magic, int cooldown)
		{
			magics [magic] = CreateMagic (magic, cooldown);
		}

		private static Magic CreateMagic(string magicName, int cooldown)
		{
			switch (magicName) 
			{
			case "ZShape":
				return new ZMagic(magicName, cooldown);
			case "OShape":
				return new OMagic(magicName, cooldown);
			case "VShape":
				return new VMagic(magicName, cooldown);
			case "throw":
				return new ThrowMagic(magicName);
			default:
				return null;
			}
		}
	}
}

