//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using HarryPotter.Magics;
namespace HarryPotter.Magics
{
	public abstract class OffensiveMagic : Magic
	{
		public static ThrowMagic throwMagic;

		public OffensiveMagic (string magicName, int cooldown) : base(magicName)
		{
			this.cooldown = cooldown;
			throwMagic = MagicFactory.GetMagic ("throw") as ThrowMagic;
		}

		public OffensiveMagic (string magicName) : base(magicName)
		{
			cooldown = 0;
		}

		protected override void Activate()
		{
			throwMagic = MagicFactory.GetMagic ("throw") as ThrowMagic;
			//Effect ();
			throwMagic.magics.Enqueue (this);
		}
	}
}

