//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

namespace HarryPotter.Magics
{
	public class VMagic : OffensiveMagic
	{	
		public GameObject hand;
		public GameObject lightningObject;

		public VMagic (string magicName, int cooldown) : base(magicName)
		{
			hand = GameObject.FindGameObjectWithTag ("hand");
			if (hand == null)
				Debug.Log ("null hand");
			lightningObject = GameObject.FindGameObjectWithTag ("lightningObject");
			if (lightningObject == null)
				Debug.Log ("null lightningObject");
			this.cooldown = cooldown;
		}

		public override void Effect()
		{
			
			Debug.Log ("EFFECT V !!!");

			Ray ray = new Ray();

			RaycastHit rHit;

			ray.origin = hand.transform.position;
			ray.direction = hand.transform.forward;

			Physics.Raycast (ray, out rHit);

			GameObject lightning = (GameObject)MonoBehaviour.Instantiate(lightningObject);
			
			//lightning.transform.position = (hand.transform.position + rHit.transform.position)/2;

			lightning.transform.position = (hand.transform.position + Vector3.forward * 10)/2;

			lightning.transform.position += Vector3.down * 5;

			//Vector3 pathBetween = rHit.transform.position - hand.transform.position;
			Vector3 pathBetween = Vector3.forward * 100;
			
			lightning.transform.eulerAngles = new Vector3(90,180  + Mathf.Rad2Deg * Mathf.Atan( (float)pathBetween.x / pathBetween.z ),180 );
			
			lightning.transform.localScale = pathBetween.magnitude/80 * Vector3.one;

			MonoBehaviour.Destroy ( lightning , 10f);
		}
	}
}

